spring:
#  config:
#    import: application-key.yml

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}

  jpa:
    # Check for transfer query
    show-sql: true
    properties:
      hibernate:
        format_sql: true

    # execute data.sql After Created table
    defer-datasource-initialization: true

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
  h2:
    console:
      enabled: true

jwt:
  issuer: ${ISSUER}
  secret_key: ${SECRET_KEY}