spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${{secrets.GOOGLE_CLIENT_ID}}
            client-secret: ${{secrets.GOOGLE_CLIENT_SECRET}}

  jpa:
    # Check for transfer query
    show-sql: true
    properties:
      hibernate:
        format_sql: true

    # execute data.sql After Created table
    defer-datasource-initialization: true

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
  h2:
    console:
      enabled: true

jwt:
  issuer: ${{secrets.ISSUER}}
  secret_key: ${{secrets.SECRET_KEY}}