# 워크플로우 이름 지정
name: AWS Test

# 워크플로우가 시작될 조건 지정
on:
  push:
    branches: [ main ]

env:
  KEY_DIR: src/main/resources
  KEY_DIR_FILE_NAME: application-key.yml
  AWS_REGION: ap-northeast-2
  S3_BUCKET_NAME: blog-deploy

# OIDC에 쓰이는 ID 토큰 발급을 위해 정의
permissions:
  id-token: write
  contents: read    # This is required for actions/checkout

jobs:
  test:
    runs-on: ubuntu-latest # 실행 환경 지정
    # 실행 스탭 지정
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      # AWS OIDC
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}
