# 워크플로우 이름 지정
name: CI

# 워크플로우가 시작될 조건 지정
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest # 실행 환경 지정
    # 실행 스탭 지정
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Copy Secrets
        env:
          KEY_DIR: src/main/resources
          GOOGLE_CLIENT_ID: ${{secrets.GOOGLE_CLIENT_ID}}
          GOOGLE_CLIENT_SECRET: ${{secrets.GOOGLE_CLIENT_SECRET}}
          ISSUER: ${{secrets.ISSUER}}
          KEY_DIR_FILE_NAME: application-key.yml
        run:
          mkdir -p $KEY_DIR
          touch $KEY_DIR_FILE_NAME
          echo $GOOGLE_CLIENT_ID | base64 --decode >> $KEY_DIR/$KEY_DIR_FILE_NAME &&
          echo $GOOGLE_CLIENT_SECRET | base64 --decode >> $KEY_DIR/$KEY_DIR_FILE_NAME &&
          echo $ISSUER | base64 --decode >> $KEY_DIR/$KEY_DIR_FILE_NAME &&
          echo $KEY_DIR_FILE_NAME | base64 --decode >> $KEY_DIR/$KEY_DIR_FILE_NAME


      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build