# 워크플로우 이름 지정
name: CI

# 워크플로우가 시작될 조건 지정
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest # 실행 환경 지정
    # 실행 스탭 지정
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      # Github Repository Secrets를 통해 application-key.yml 파일 생성
      - name: Generate Key File
        run: |
          echo "GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID" >> application-key.yml
          echo "GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET" >> application-key.yml
          echo "ISSUER=$ISSUER" >> application-key.yml
          echo "SECRET_KEY=$SECRET_KEY" >> application-key.yml

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build